[tool.poetry]
name = "auth-onedrive"
version = "0.1.0"
description = ""
authors = ["Christian Bueno <chmabuen@espol.edu.ec>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
msal = "^1.30.0"
requests = "^2.32.3"
msgraph-core = "^1.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# script
[tool.poetry.scripts]
start = "auth_onedrive.main:app"